# General settings
experiment_name: " debug"
output_dir: "saved_models"  
# Data configuration
data:
  data_path: "data/sevennet_slopes.csv"
  target_column: "v1_Li_slope"
  temperature: 1000
  noise_std: 0.01
  batch_size: 3
  num_workers: 4  
  test_size: 0.2
  random_state: 42
  clip_value: 0.0001

model:
  radial_cutoff: 5
  num_neighbors: 50
  pool_nodes: False

# Training hyperparameters
training:
  learning_rate: 0.001
  num_agg: 3
  optimizer: "Adam"  
  criterion: "MSELoss"  
  num_epochs: 500
  device: "cuda:0"
  verbose: False
  save_model_every_n_epochs: 20
  forces_divided_by_mass: True
  shift: True
  predict_importance: False
  
property_predictor:
  name: "sevennet"
  checkpoint: "7net-0"
  
wandb:
  verbose: False
  project_name: "LiCondEquivariantModel"
  entity_name: "licondequvariantmodel"