# General settings
experiment_name: "num_neighbors_50_forces_divided_by_mass_false_2"
output_dir: "saved_models"  
# Data configuration
data:
  data_path: "data/sevennet_slopes.csv"
  target_column: "v1_Li_slope"
  temperature: 1000
  noise_std: 0.01
  batch_size: 20
  num_workers: 4  
  test_size: 0.2
  random_state: 42
  clip_value: 0.0001

# Training hyperparameters
training:
  radial_cutoff: 5
  num_neighbors: 50
  learning_rate: 0.001
  optimizer: "Adam"  
  criterion: "MSELoss"  
  num_epochs: 500
  device: "cuda:1"
  verbose: False
  save_model_every_n_epochs: 20
  forces_divided_by_mass: False
  
property_predictor:
  name: "sevennet"
  checkpoint: "7net-0"
wandb:
  project_name: "LiCondEquivariantModel"
  entity_name: "licondequvariantmodel"