# General settings
experiment_name: "baseline_noise_0.1"
comment: "the simpliest version of model and pipeline
          there is no importance prediction and noise structures aggregation"
output_dir: "saved_models"  

# Data configuration
data:
  data_path: "data/sevennet_slopes.csv"
  target_column: "v1_Li_slope"
  temperature: 1000
  noise_std: 0.1 
  batch_size: 10
  num_workers: 4  
  test_size: 0.2
  random_state: 42
  clip_value: 0.0001

model:
  radial_cutoff: 5
  num_neighbors: 50
  predict_importance: False
  pool_nodes: False
  num_nodes: 1.0

# Training hyperparameters
training:
  learning_rate: 0.001
  num_noisy_configurations: 1
  optimizer: "Adam"
  criterion: "MSELoss"  
  num_epochs: 500
  device: "cuda:1"
  save_model_every_n_epochs: 5
  forces_divided_by_mass: True
  use_displacements: False
  use_energies: False
  softmax_within_single_structure_by_configurations: False
  softmax_within_single_atom_by_configurations: False
  softmax_within_configurations: True

property_predictor:
  name: "sevennet"
  checkpoint: "7net-0"
  batch_size: 50
  
wandb:
  verbose: True
  project_name: "LiCondEquivariantModel"
  entity_name: "licondequvariantmodel"

