# General settings
experiment_name: "noise_0.1_noisy_config_5_importance_False_const_lr_0.0001"
comment: "structures aggregation"
output_dir: "/mnt/hdd/turchina/saved_models" 
 
# Data configuration
data:
  data_path: "data/sevennet_slopes.csv"
  target_column: "v1_Li_slope"
  temperature: 1000
  noise_std: 0.1 
  batch_size: 10
  num_workers: 4  
  test_size: 0.2
  random_state: 42
  clip_value: 0.0001

model:
  radial_cutoff: 5
  num_neighbors: 50
  predict_importance: False
  pool_nodes: False
  num_nodes: 1.0

scheduler:
  constant_lr: True
  warmup_scheduler: "LinearLR"
  warmup_epochs: 5
  warmup_decay: 0.01
  main_scheduler: "CosineAnnealingLR"

optimizer:
  name: "Adam"
  learning_rate: 0.0001

# Training hyperparameters
training:
  num_noisy_configurations: 5
  criterion: "MSELoss"  
  num_epochs: 500
  device: "cuda:0"
  save_model_every_n_epochs: 20
  forces_divided_by_mass: True
  use_displacements: False
  use_energies: False
  softmax_within_single_structure_by_configurations: False
  softmax_within_single_atom_by_configurations: False
  softmax_within_configurations: True

property_predictor:
  name: "superionic_toy"
  property_config:
    factory_name: linear_combination
    params:
      calcs:
      - factory_name: pairwise_harmonic
        params:
          base_k_value: 0.5
          k_uniform_width: 0.5
          min_neighbors: 12
          random_seed: 42
      - factory_name: pairwise_arbitrary
        params:
          potential: lj
          r0: 4.0
      weights:
      - 1.0
      - 0.1
  choose_mobile_species_params:
    random_seed: 42
    strategy: inv_mass_weighted
    
wandb:
  verbose: True
  project_name: "LiCondEquivariantModel"
  entity_name: "licondequvariantmodel"

