# General settings
experiment_name: "LennardJones"
comment: "structures aggregation"
output_dir: "/mnt/hdd/turchina/saved_models" 
 
# Data configuration
data:
  data_path: "data/sevennet_slopes.csv"
  target_column: "v1_Li_slope"
  temperature: 1000
  noise_std: 0.1 
  batch_size: 10
  num_workers: 4  
  test_size: 0.2
  random_state: 42
  clip_value: 0.0001
  upd_neigh_style: "update_class"

model:
  radial_cutoff: 5
  num_neighbors: 50
  predict_importance: False
  pool_nodes: False
  num_nodes: 1.0

scheduler:
  constant_lr: True
  warmup_scheduler: "LinearLR"
  warmup_epochs: 5
  warmup_decay: 0.01
  main_scheduler: "CosineAnnealingLR"

optimizer:
  name: "Adam"
  learning_rate: 0.0001

# Training hyperparameters
training:
  num_noisy_configurations: 5
  criterion: "MSELoss"  
  num_epochs: 500
  device: "cuda:0"
  save_model_every_n_epochs: 20
  forces_divided_by_mass: False
  use_displacements: False
  use_energies: False
  softmax_within_single_structure_by_configurations: False
  softmax_within_single_atom_by_configurations: False
  softmax_within_configurations: True

property_predictor:
  name: "LennardJones"
  property_config:
    sigma: 2
  
wandb:
  verbose: False
  project_name: "LiCondEquivariantModel"
  entity_name: "licondequvariantmodel"

