name: python unit tests
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pytest-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu
          pip install '.[test]'

      - name: Pytest install
        run: |
          pip install pytest

      - name: Run unit test
        run: |
          pytest tests/unit_tests
